apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment 
  labels:
    app: auth-service 
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: auth-service 
  template: 
    metadata:
      labels:
        app: auth-service 
    spec:
      containers:
      - name: auth-service-container
        image: AUTH_IMAGE_PLACEHOLDER # <-- Jenkins will replace this
        ports:
        - containerPort: 5001 
        env:
          - name: FLASK_RUN_PORT
            value: "5001"
          - name: FLASK_RUN_HOST
            value: "0.0.0.0"
          
        resources: 
          requests:
            memory: "64Mi"
            cpu: "100m" # 100 millicpu (0.1 CPU)
          limits:
            memory: "128Mi"
            cpu: "250m"