apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# List all resource files to include
resources:
  - auth-deployment.yaml
  - auth-service.yaml
  - video-deployment.yaml
  - video-service.yaml

# Common labels to add to all resources
commonLabels:
  app.kubernetes.io/managed-by: kustomize
  project: devops-microservices-practice

