apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-deployment
  labels:
    app: video-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: video-service
  template:
    metadata:
      labels:
        app: video-service
    spec:
      containers:
      - name: video-service-container
        image: VIDEO_IMAGE_PLACEHOLDER # <-- Jenkins will replace this
        ports:
        - containerPort: 5002
        env:
          - name: FLASK_RUN_PORT
            value: "5002"
          - name: FLASK_RUN_HOST
            value: "0.0.0.0"
          
          - name: AUTH_SERVICE_URL
            value: "http://auth-service:5001" 
        
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"