---
- name: Configure Base Tools on Linux Agent
  hosts: jenkins_agents 
  become: yes
  tasks:
    - name: Install essential packages
      apt:
        name: ['git', 'curl', 'unzip']
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install essential packages 
      yum:
        name: ['git', 'curl', 'unzip']
        state: present
        update_cache: yes
      when: ansible_os_family == "RedHat"

